# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'exercise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'CodableAlamofire'
  pod 'AlamofireImage'

  # Pods for exercise

  target 'exerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'exerciseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
